# Each route describes how a url will be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "ll_project:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"